### ISSUE TITLE
Missing libjpeg.so.8

### ISSUE THREAD

**Issue by eard7** [node-3d/deps-freeimage-raub#1]
Hello @raub !
Thanks for the great effort you're doing on this suite.
Just found an issue running a project in my CentOS lately in which looks like there's a missing dependency

```
Error: libjpeg.so.8: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/erivera/image-service/node_modules/image-raub/core.js:10:14)

```

After inspecting the dependencies from deps-freeimage, it actually has `libjpeg.so.62`, but it's missing `libjpeg.so.8`. Something curious is that in an older version of the package the dependency is there. The issue is fixed if I copy/paste the missing lib.
Currently testing on 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```
Not sure if this is the right place to raise the issue or if I should've created it on the image-raub project.
Hope you can take a look onto this.
Thanks!

**Comment by raub** [comment]
Hello! I have added the old `libjpeg.so.8` to the current binary package. Please try if it works for you now without manual copying.

I suppose it was missing because it is not needed on Ubuntu Xenial - the only type of Linux I "have" and "officially" support.
